# Generated by Django 5.1.2 on 2024-10-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=200, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('rut', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('member_type', models.CharField(max_length=200)),
                ('observation', models.CharField(max_length=250)),
            ],
        ),
    ]
