# Generated by Django 5.1.2 on 2024-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='id_code',
            field=models.CharField(max_length=200),
        ),
    ]
