# Generated by Django 5.1.2 on 2024-10-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_rut_alter_validation_id_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_code',
        ),
        migrations.AddField(
            model_name='records',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
